[platformio]
default_envs = seeed_xiao_esp32c6

[env:seeed_xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = espidf
build_flags = -Os
build_type = release

[env:native]
platform = native
lib_ignore = fakeap
test_framework = unity
build_src_filter = -<*>
