[platformio]
default_envs = seeed_xiao_esp32c6

[env:seeed_xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = espidf
build_flags = -Os -Iinclude
build_type = release

; Explicitly point PlatformIO to the 4MB maximum-allocation map
board_build.partitions = partitions.csv

; Serve the web control panel from SPIFFS (see partitions.csv "storage")
board_build.filesystem = spiffs
board_upload.flash_size = 4MB

; fucking nimble frames
lib_ldf_mode = deep+

[env:native]
platform = native
lib_ignore = fakeap
lib_extra_dirs = components
test_framework = unity
build_src_filter = -<*>
build_flags = -Iinclude


