#include <string.h>

char *CUSTOM_SSIDS[] = {
    "MIMI",
    "HAJA",
    "KUPKA",
    // "Click Here for Viruses",
    // "Please Connect for Identity Theft",
    // "Credit Card Hacker",
    // "Gone Phishing",
    // "I Am Watching You",
    // "I’m Under Your Bed",
    // "Your Data Is Mine",
    // "Virus Upload Complete",
    // "NSA Listening Post",
    // "We Know Where You Live",
    // "Troy Has a Virus",
    // "Definitely Not a Trap",
    // "Malware Distribution Center",
    // "Hacked and Loving It",
    // "Your Webcam Is On",
    // "The Smith Family Wifi",
    // "Mom Click Here",
    // "Password is Password",
    // "No Free Wifi Here",
    // "Please Bring Wine",
    // "We Can Hear You Talking",
    // "Close Your Curtains",
    // "My Neighbors Suck",
    // "Thou Shalt Not Covet Thy Neighbor’s Wifi",
    // "Hey Get Your Own Wifi",
    // "Our Internet Is Faster Than Yours",
    // "I Did Your Wifi Last Night",
    // "The Creep Next Door",
    // "Bob’s Unsecured House of Wifi",
    // "Reserved for Guests I Hate",
    // "Abraham Linksys",
    // "Benjamin FrankLAN",
    // "Theodore Routervelt",
    // "John Wilkes Bluetooth",
    // "Vladimir Computin",
    // "John Claude WAN Damme",
    // "LAN Morrison",
    // "Bob DyLAN",
    // "Winona Router",
    // "Chance the Router",
    // "The Silence of the LANs",
    // "Alice in WonderLAN",
    // "Winter WonderLAN",
    // "The Promised LAN",
    // "Life in the Fast LAN",
    // "No LAN for the Wicked",
    // "One if by LAN",
    // "Silence of the LAN",
    // "Comcasterly Rock",
    // "Franklin Delano Routervelt",
    NULL,
};
