#include <string.h>

char *CUSTOM_SSIDS[] = {
    "this is fake 1",
    "this is fake 2",
    "this is fake 3",
    "this is fake 4",
    "this is fake 5",
    "this is fake 6",
    "this is fake 7",
    "this is fake 8",
    "this is fake 9",
    "this is fake 10",
    "this is fake 11",
    "this is fake 12",
    "this is fake 13",
    "this is fake 14",
    "this is fake 15",
    "this is fake 16",
    "this is fake 17",
    "this is fake 18",
    "this is fake 19",
    "this is fake 20",
    "this is fake 21",
    "this is fake 22",
    "this is fake 23",
    "this is fake 24",
    "this is fake 25",
    "this is fake 26",
    "this is fake 27",
    "this is fake 28",
    "this is fake 29",
    "this is fake 30",
    "this is fake 31",
    "this is fake 32",
    "this is fake 33",
    "this is fake 34",
    "this is fake 35",
    "this is fake 36",
    "this is fake 37",

    // "Click Here for Viruses",
    // "Please Connect for Identity Theft",
    // "Credit Card Hacker",
    // "Gone Phishing",
    // "I Am Watching You",
    // "I’m Under Your Bed",
    // "Your Data Is Mine",
    // "Virus Upload Complete",
    // "NSA Listening Post",
    // "We Know Where You Live",
    // "Troy Has a Virus",
    // "Definitely Not a Trap",
    // "Malware Distribution Center",
    // "Hacked and Loving It",
    // "Your Webcam Is On",
    // "The Smith Family Wifi",
    // "Mom Click Here",
    // "Password is Password",
    // "No Free Wifi Here",
    // "Please Bring Wine",
    // "We Can Hear You Talking",
    // "Close Your Curtains",
    // "My Neighbors Suck",
    // "Thou Shalt Not Covet Thy Neighbor’s Wifi",
    // "Hey Get Your Own Wifi",
    // "Our Internet Is Faster Than Yours",
    // "I Did Your Wifi Last Night",
    // "The Creep Next Door",
    // "Bob’s Unsecured House of Wifi",
    // "Reserved for Guests I Hate",
    // "Abraham Linksys",
    // "Benjamin FrankLAN",
    // "Theodore Routervelt",
    // "John Wilkes Bluetooth",
    // "Vladimir Computin",
    // "John Claude WAN Damme",
    // "LAN Morrison",
    // "Bob DyLAN",
    // "Winona Router",
    // "Chance the Router",
    // "The Silence of the LANs",
    // "Alice in WonderLAN",
    // "Winter WonderLAN",
    // "The Promised LAN",
    // "Life in the Fast LAN",
    // "No LAN for the Wicked",
    // "One if by LAN",
    // "Silence of the LAN",
    // "Comcasterly Rock",
    // "Franklin Delano Routervelt",
    NULL,
};
